version: '3'

services:
  app:
    image: yiluxiangbei/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 8091:3002
    environment:
      OPENAI_API_KEY: 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
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL: https://openai-api.luomor.com
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL: gpt-3.5-turbo
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
  nginx:
    image: nginx:alpine
    ports:
      - '8090:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
